### ISSUE TITLE
yardım

### ISSUE THREAD

**Issue by Muzcuk237529** [Muhammedska/maks-blocker#1]
reis bunu nasıl usb ile autorun yaparız akıllı tahtalarda otomatik oynatma açık oluyor da

**Comment by Muhammedska** [comment]
> reis bunu nasıl usb ile autorun yaparız akıllı tahtalarda otomatik oynatma açık oluyor da

hocam Windows usbler için autorun yapan yazılımlar var lakin çoğu sağlıklı çalışmıyor teşekkürler
